<?php include "home.php"; ?>
<?php include "overview.php"; ?>
<?php include "team.php"; ?>
<?php include "client.php"; ?>
<?php include "methodology.php"; ?>
<?php include "faq.php"; ?>
<?php include "social.php"; ?>
<?php include "portfolio.php"; ?>
<?php include "testimonial.php"; ?>
<?php include "get_started.php"; ?>
<?php include "splashdata.php"; ?>
<?php include "sidebar.php"; ?>