package com.audacityit.audacity.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.audacityit.audacity.greendao.db.SlideBarGR;
import com.audacityit.audacity.greendao.db.SplashGR;
import com.audacityit.audacity.greendao.db.OverviewcontentGR;
import com.audacityit.audacity.greendao.db.OverviewGR;
import com.audacityit.audacity.greendao.db.OverviewitemsGR;
import com.audacityit.audacity.greendao.db.HomeGR;
import com.audacityit.audacity.greendao.db.HomeGR_;
import com.audacityit.audacity.greendao.db.PortfolioGR;
import com.audacityit.audacity.greendao.db.PortfolioGR_;
import com.audacityit.audacity.greendao.db.PTagGR;
import com.audacityit.audacity.greendao.db.ClientGR;
import com.audacityit.audacity.greendao.db.ClientGR_;
import com.audacityit.audacity.greendao.db.ClientTag;
import com.audacityit.audacity.greendao.db.GetstartedGR;
import com.audacityit.audacity.greendao.db.GetstartedTag;
import com.audacityit.audacity.greendao.db.TeamGR;
import com.audacityit.audacity.greendao.db.TeamGR_;
import com.audacityit.audacity.greendao.db.MethodologyGR;
import com.audacityit.audacity.greendao.db.MethodologyGR_;
import com.audacityit.audacity.greendao.db.MethodologyItemGR;
import com.audacityit.audacity.greendao.db.FqaGR;
import com.audacityit.audacity.greendao.db.FqaGR_;
import com.audacityit.audacity.greendao.db.TestimonialGR;
import com.audacityit.audacity.greendao.db.TestimonialGR_;
import com.audacityit.audacity.greendao.db.SocialGR;
import com.audacityit.audacity.greendao.db.SocialGR_;

import com.audacityit.audacity.greendao.db.SlideBarGRDao;
import com.audacityit.audacity.greendao.db.SplashGRDao;
import com.audacityit.audacity.greendao.db.OverviewcontentGRDao;
import com.audacityit.audacity.greendao.db.OverviewGRDao;
import com.audacityit.audacity.greendao.db.OverviewitemsGRDao;
import com.audacityit.audacity.greendao.db.HomeGRDao;
import com.audacityit.audacity.greendao.db.HomeGR_Dao;
import com.audacityit.audacity.greendao.db.PortfolioGRDao;
import com.audacityit.audacity.greendao.db.PortfolioGR_Dao;
import com.audacityit.audacity.greendao.db.PTagGRDao;
import com.audacityit.audacity.greendao.db.ClientGRDao;
import com.audacityit.audacity.greendao.db.ClientGR_Dao;
import com.audacityit.audacity.greendao.db.ClientTagDao;
import com.audacityit.audacity.greendao.db.GetstartedGRDao;
import com.audacityit.audacity.greendao.db.GetstartedTagDao;
import com.audacityit.audacity.greendao.db.TeamGRDao;
import com.audacityit.audacity.greendao.db.TeamGR_Dao;
import com.audacityit.audacity.greendao.db.MethodologyGRDao;
import com.audacityit.audacity.greendao.db.MethodologyGR_Dao;
import com.audacityit.audacity.greendao.db.MethodologyItemGRDao;
import com.audacityit.audacity.greendao.db.FqaGRDao;
import com.audacityit.audacity.greendao.db.FqaGR_Dao;
import com.audacityit.audacity.greendao.db.TestimonialGRDao;
import com.audacityit.audacity.greendao.db.TestimonialGR_Dao;
import com.audacityit.audacity.greendao.db.SocialGRDao;
import com.audacityit.audacity.greendao.db.SocialGR_Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig slideBarGRDaoConfig;
    private final DaoConfig splashGRDaoConfig;
    private final DaoConfig overviewcontentGRDaoConfig;
    private final DaoConfig overviewGRDaoConfig;
    private final DaoConfig overviewitemsGRDaoConfig;
    private final DaoConfig homeGRDaoConfig;
    private final DaoConfig homeGR_DaoConfig;
    private final DaoConfig portfolioGRDaoConfig;
    private final DaoConfig portfolioGR_DaoConfig;
    private final DaoConfig pTagGRDaoConfig;
    private final DaoConfig clientGRDaoConfig;
    private final DaoConfig clientGR_DaoConfig;
    private final DaoConfig clientTagDaoConfig;
    private final DaoConfig getstartedGRDaoConfig;
    private final DaoConfig getstartedTagDaoConfig;
    private final DaoConfig teamGRDaoConfig;
    private final DaoConfig teamGR_DaoConfig;
    private final DaoConfig methodologyGRDaoConfig;
    private final DaoConfig methodologyGR_DaoConfig;
    private final DaoConfig methodologyItemGRDaoConfig;
    private final DaoConfig fqaGRDaoConfig;
    private final DaoConfig fqaGR_DaoConfig;
    private final DaoConfig testimonialGRDaoConfig;
    private final DaoConfig testimonialGR_DaoConfig;
    private final DaoConfig socialGRDaoConfig;
    private final DaoConfig socialGR_DaoConfig;

    private final SlideBarGRDao slideBarGRDao;
    private final SplashGRDao splashGRDao;
    private final OverviewcontentGRDao overviewcontentGRDao;
    private final OverviewGRDao overviewGRDao;
    private final OverviewitemsGRDao overviewitemsGRDao;
    private final HomeGRDao homeGRDao;
    private final HomeGR_Dao homeGR_Dao;
    private final PortfolioGRDao portfolioGRDao;
    private final PortfolioGR_Dao portfolioGR_Dao;
    private final PTagGRDao pTagGRDao;
    private final ClientGRDao clientGRDao;
    private final ClientGR_Dao clientGR_Dao;
    private final ClientTagDao clientTagDao;
    private final GetstartedGRDao getstartedGRDao;
    private final GetstartedTagDao getstartedTagDao;
    private final TeamGRDao teamGRDao;
    private final TeamGR_Dao teamGR_Dao;
    private final MethodologyGRDao methodologyGRDao;
    private final MethodologyGR_Dao methodologyGR_Dao;
    private final MethodologyItemGRDao methodologyItemGRDao;
    private final FqaGRDao fqaGRDao;
    private final FqaGR_Dao fqaGR_Dao;
    private final TestimonialGRDao testimonialGRDao;
    private final TestimonialGR_Dao testimonialGR_Dao;
    private final SocialGRDao socialGRDao;
    private final SocialGR_Dao socialGR_Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        slideBarGRDaoConfig = daoConfigMap.get(SlideBarGRDao.class).clone();
        slideBarGRDaoConfig.initIdentityScope(type);

        splashGRDaoConfig = daoConfigMap.get(SplashGRDao.class).clone();
        splashGRDaoConfig.initIdentityScope(type);

        overviewcontentGRDaoConfig = daoConfigMap.get(OverviewcontentGRDao.class).clone();
        overviewcontentGRDaoConfig.initIdentityScope(type);

        overviewGRDaoConfig = daoConfigMap.get(OverviewGRDao.class).clone();
        overviewGRDaoConfig.initIdentityScope(type);

        overviewitemsGRDaoConfig = daoConfigMap.get(OverviewitemsGRDao.class).clone();
        overviewitemsGRDaoConfig.initIdentityScope(type);

        homeGRDaoConfig = daoConfigMap.get(HomeGRDao.class).clone();
        homeGRDaoConfig.initIdentityScope(type);

        homeGR_DaoConfig = daoConfigMap.get(HomeGR_Dao.class).clone();
        homeGR_DaoConfig.initIdentityScope(type);

        portfolioGRDaoConfig = daoConfigMap.get(PortfolioGRDao.class).clone();
        portfolioGRDaoConfig.initIdentityScope(type);

        portfolioGR_DaoConfig = daoConfigMap.get(PortfolioGR_Dao.class).clone();
        portfolioGR_DaoConfig.initIdentityScope(type);

        pTagGRDaoConfig = daoConfigMap.get(PTagGRDao.class).clone();
        pTagGRDaoConfig.initIdentityScope(type);

        clientGRDaoConfig = daoConfigMap.get(ClientGRDao.class).clone();
        clientGRDaoConfig.initIdentityScope(type);

        clientGR_DaoConfig = daoConfigMap.get(ClientGR_Dao.class).clone();
        clientGR_DaoConfig.initIdentityScope(type);

        clientTagDaoConfig = daoConfigMap.get(ClientTagDao.class).clone();
        clientTagDaoConfig.initIdentityScope(type);

        getstartedGRDaoConfig = daoConfigMap.get(GetstartedGRDao.class).clone();
        getstartedGRDaoConfig.initIdentityScope(type);

        getstartedTagDaoConfig = daoConfigMap.get(GetstartedTagDao.class).clone();
        getstartedTagDaoConfig.initIdentityScope(type);

        teamGRDaoConfig = daoConfigMap.get(TeamGRDao.class).clone();
        teamGRDaoConfig.initIdentityScope(type);

        teamGR_DaoConfig = daoConfigMap.get(TeamGR_Dao.class).clone();
        teamGR_DaoConfig.initIdentityScope(type);

        methodologyGRDaoConfig = daoConfigMap.get(MethodologyGRDao.class).clone();
        methodologyGRDaoConfig.initIdentityScope(type);

        methodologyGR_DaoConfig = daoConfigMap.get(MethodologyGR_Dao.class).clone();
        methodologyGR_DaoConfig.initIdentityScope(type);

        methodologyItemGRDaoConfig = daoConfigMap.get(MethodologyItemGRDao.class).clone();
        methodologyItemGRDaoConfig.initIdentityScope(type);

        fqaGRDaoConfig = daoConfigMap.get(FqaGRDao.class).clone();
        fqaGRDaoConfig.initIdentityScope(type);

        fqaGR_DaoConfig = daoConfigMap.get(FqaGR_Dao.class).clone();
        fqaGR_DaoConfig.initIdentityScope(type);

        testimonialGRDaoConfig = daoConfigMap.get(TestimonialGRDao.class).clone();
        testimonialGRDaoConfig.initIdentityScope(type);

        testimonialGR_DaoConfig = daoConfigMap.get(TestimonialGR_Dao.class).clone();
        testimonialGR_DaoConfig.initIdentityScope(type);

        socialGRDaoConfig = daoConfigMap.get(SocialGRDao.class).clone();
        socialGRDaoConfig.initIdentityScope(type);

        socialGR_DaoConfig = daoConfigMap.get(SocialGR_Dao.class).clone();
        socialGR_DaoConfig.initIdentityScope(type);

        slideBarGRDao = new SlideBarGRDao(slideBarGRDaoConfig, this);
        splashGRDao = new SplashGRDao(splashGRDaoConfig, this);
        overviewcontentGRDao = new OverviewcontentGRDao(overviewcontentGRDaoConfig, this);
        overviewGRDao = new OverviewGRDao(overviewGRDaoConfig, this);
        overviewitemsGRDao = new OverviewitemsGRDao(overviewitemsGRDaoConfig, this);
        homeGRDao = new HomeGRDao(homeGRDaoConfig, this);
        homeGR_Dao = new HomeGR_Dao(homeGR_DaoConfig, this);
        portfolioGRDao = new PortfolioGRDao(portfolioGRDaoConfig, this);
        portfolioGR_Dao = new PortfolioGR_Dao(portfolioGR_DaoConfig, this);
        pTagGRDao = new PTagGRDao(pTagGRDaoConfig, this);
        clientGRDao = new ClientGRDao(clientGRDaoConfig, this);
        clientGR_Dao = new ClientGR_Dao(clientGR_DaoConfig, this);
        clientTagDao = new ClientTagDao(clientTagDaoConfig, this);
        getstartedGRDao = new GetstartedGRDao(getstartedGRDaoConfig, this);
        getstartedTagDao = new GetstartedTagDao(getstartedTagDaoConfig, this);
        teamGRDao = new TeamGRDao(teamGRDaoConfig, this);
        teamGR_Dao = new TeamGR_Dao(teamGR_DaoConfig, this);
        methodologyGRDao = new MethodologyGRDao(methodologyGRDaoConfig, this);
        methodologyGR_Dao = new MethodologyGR_Dao(methodologyGR_DaoConfig, this);
        methodologyItemGRDao = new MethodologyItemGRDao(methodologyItemGRDaoConfig, this);
        fqaGRDao = new FqaGRDao(fqaGRDaoConfig, this);
        fqaGR_Dao = new FqaGR_Dao(fqaGR_DaoConfig, this);
        testimonialGRDao = new TestimonialGRDao(testimonialGRDaoConfig, this);
        testimonialGR_Dao = new TestimonialGR_Dao(testimonialGR_DaoConfig, this);
        socialGRDao = new SocialGRDao(socialGRDaoConfig, this);
        socialGR_Dao = new SocialGR_Dao(socialGR_DaoConfig, this);

        registerDao(SlideBarGR.class, slideBarGRDao);
        registerDao(SplashGR.class, splashGRDao);
        registerDao(OverviewcontentGR.class, overviewcontentGRDao);
        registerDao(OverviewGR.class, overviewGRDao);
        registerDao(OverviewitemsGR.class, overviewitemsGRDao);
        registerDao(HomeGR.class, homeGRDao);
        registerDao(HomeGR_.class, homeGR_Dao);
        registerDao(PortfolioGR.class, portfolioGRDao);
        registerDao(PortfolioGR_.class, portfolioGR_Dao);
        registerDao(PTagGR.class, pTagGRDao);
        registerDao(ClientGR.class, clientGRDao);
        registerDao(ClientGR_.class, clientGR_Dao);
        registerDao(ClientTag.class, clientTagDao);
        registerDao(GetstartedGR.class, getstartedGRDao);
        registerDao(GetstartedTag.class, getstartedTagDao);
        registerDao(TeamGR.class, teamGRDao);
        registerDao(TeamGR_.class, teamGR_Dao);
        registerDao(MethodologyGR.class, methodologyGRDao);
        registerDao(MethodologyGR_.class, methodologyGR_Dao);
        registerDao(MethodologyItemGR.class, methodologyItemGRDao);
        registerDao(FqaGR.class, fqaGRDao);
        registerDao(FqaGR_.class, fqaGR_Dao);
        registerDao(TestimonialGR.class, testimonialGRDao);
        registerDao(TestimonialGR_.class, testimonialGR_Dao);
        registerDao(SocialGR.class, socialGRDao);
        registerDao(SocialGR_.class, socialGR_Dao);
    }
    
    public void clear() {
        slideBarGRDaoConfig.getIdentityScope().clear();
        splashGRDaoConfig.getIdentityScope().clear();
        overviewcontentGRDaoConfig.getIdentityScope().clear();
        overviewGRDaoConfig.getIdentityScope().clear();
        overviewitemsGRDaoConfig.getIdentityScope().clear();
        homeGRDaoConfig.getIdentityScope().clear();
        homeGR_DaoConfig.getIdentityScope().clear();
        portfolioGRDaoConfig.getIdentityScope().clear();
        portfolioGR_DaoConfig.getIdentityScope().clear();
        pTagGRDaoConfig.getIdentityScope().clear();
        clientGRDaoConfig.getIdentityScope().clear();
        clientGR_DaoConfig.getIdentityScope().clear();
        clientTagDaoConfig.getIdentityScope().clear();
        getstartedGRDaoConfig.getIdentityScope().clear();
        getstartedTagDaoConfig.getIdentityScope().clear();
        teamGRDaoConfig.getIdentityScope().clear();
        teamGR_DaoConfig.getIdentityScope().clear();
        methodologyGRDaoConfig.getIdentityScope().clear();
        methodologyGR_DaoConfig.getIdentityScope().clear();
        methodologyItemGRDaoConfig.getIdentityScope().clear();
        fqaGRDaoConfig.getIdentityScope().clear();
        fqaGR_DaoConfig.getIdentityScope().clear();
        testimonialGRDaoConfig.getIdentityScope().clear();
        testimonialGR_DaoConfig.getIdentityScope().clear();
        socialGRDaoConfig.getIdentityScope().clear();
        socialGR_DaoConfig.getIdentityScope().clear();
    }

    public SlideBarGRDao getSlideBarGRDao() {
        return slideBarGRDao;
    }

    public SplashGRDao getSplashGRDao() {
        return splashGRDao;
    }

    public OverviewcontentGRDao getOverviewcontentGRDao() {
        return overviewcontentGRDao;
    }

    public OverviewGRDao getOverviewGRDao() {
        return overviewGRDao;
    }

    public OverviewitemsGRDao getOverviewitemsGRDao() {
        return overviewitemsGRDao;
    }

    public HomeGRDao getHomeGRDao() {
        return homeGRDao;
    }

    public HomeGR_Dao getHomeGR_Dao() {
        return homeGR_Dao;
    }

    public PortfolioGRDao getPortfolioGRDao() {
        return portfolioGRDao;
    }

    public PortfolioGR_Dao getPortfolioGR_Dao() {
        return portfolioGR_Dao;
    }

    public PTagGRDao getPTagGRDao() {
        return pTagGRDao;
    }

    public ClientGRDao getClientGRDao() {
        return clientGRDao;
    }

    public ClientGR_Dao getClientGR_Dao() {
        return clientGR_Dao;
    }

    public ClientTagDao getClientTagDao() {
        return clientTagDao;
    }

    public GetstartedGRDao getGetstartedGRDao() {
        return getstartedGRDao;
    }

    public GetstartedTagDao getGetstartedTagDao() {
        return getstartedTagDao;
    }

    public TeamGRDao getTeamGRDao() {
        return teamGRDao;
    }

    public TeamGR_Dao getTeamGR_Dao() {
        return teamGR_Dao;
    }

    public MethodologyGRDao getMethodologyGRDao() {
        return methodologyGRDao;
    }

    public MethodologyGR_Dao getMethodologyGR_Dao() {
        return methodologyGR_Dao;
    }

    public MethodologyItemGRDao getMethodologyItemGRDao() {
        return methodologyItemGRDao;
    }

    public FqaGRDao getFqaGRDao() {
        return fqaGRDao;
    }

    public FqaGR_Dao getFqaGR_Dao() {
        return fqaGR_Dao;
    }

    public TestimonialGRDao getTestimonialGRDao() {
        return testimonialGRDao;
    }

    public TestimonialGR_Dao getTestimonialGR_Dao() {
        return testimonialGR_Dao;
    }

    public SocialGRDao getSocialGRDao() {
        return socialGRDao;
    }

    public SocialGR_Dao getSocialGR_Dao() {
        return socialGR_Dao;
    }

}
