package com.audacityit.audacity.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.audacityit.audacity.greendao.db.GetstartedGR;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GETSTARTED_GR".
*/
public class GetstartedGRDao extends AbstractDao<GetstartedGR, Long> {

    public static final String TABLENAME = "GETSTARTED_GR";

    /**
     * Properties of entity GetstartedGR.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Range1 = new Property(1, String.class, "range1", false, "RANGE1");
        public final static Property Range2 = new Property(2, String.class, "range2", false, "RANGE2");
        public final static Property Range3 = new Property(3, String.class, "range3", false, "RANGE3");
        public final static Property Range4 = new Property(4, String.class, "range4", false, "RANGE4");
        public final static Property Phone = new Property(5, String.class, "phone", false, "PHONE");
        public final static Property Email = new Property(6, String.class, "email", false, "EMAIL");
        public final static Property Web = new Property(7, String.class, "web", false, "WEB");
    };

    private DaoSession daoSession;


    public GetstartedGRDao(DaoConfig config) {
        super(config);
    }
    
    public GetstartedGRDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GETSTARTED_GR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RANGE1\" TEXT," + // 1: range1
                "\"RANGE2\" TEXT," + // 2: range2
                "\"RANGE3\" TEXT," + // 3: range3
                "\"RANGE4\" TEXT," + // 4: range4
                "\"PHONE\" TEXT," + // 5: phone
                "\"EMAIL\" TEXT," + // 6: email
                "\"WEB\" TEXT);"); // 7: web
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GETSTARTED_GR\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GetstartedGR entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String range1 = entity.getRange1();
        if (range1 != null) {
            stmt.bindString(2, range1);
        }
 
        String range2 = entity.getRange2();
        if (range2 != null) {
            stmt.bindString(3, range2);
        }
 
        String range3 = entity.getRange3();
        if (range3 != null) {
            stmt.bindString(4, range3);
        }
 
        String range4 = entity.getRange4();
        if (range4 != null) {
            stmt.bindString(5, range4);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
 
        String web = entity.getWeb();
        if (web != null) {
            stmt.bindString(8, web);
        }
    }

    @Override
    protected void attachEntity(GetstartedGR entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GetstartedGR readEntity(Cursor cursor, int offset) {
        GetstartedGR entity = new GetstartedGR( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // range1
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // range2
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // range3
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // range4
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // phone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // email
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // web
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GetstartedGR entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRange1(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRange2(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRange3(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRange4(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPhone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWeb(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GetstartedGR entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GetstartedGR entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
