package com.audacityit.audacity.greendao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.audacityit.audacity.greendao.db.MethodologyGR_;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "METHODOLOGY_GR_".
*/
public class MethodologyGR_Dao extends AbstractDao<MethodologyGR_, Long> {

    public static final String TABLENAME = "METHODOLOGY_GR_";

    /**
     * Properties of entity MethodologyGR_.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Background = new Property(1, String.class, "background", false, "BACKGROUND");
        public final static Property Logo = new Property(2, String.class, "logo", false, "LOGO");
        public final static Property Methodology_id = new Property(3, long.class, "methodology_id", false, "METHODOLOGY_ID");
    };

    private DaoSession daoSession;

    private Query<MethodologyGR_> methodologyGR_MethodologyGR_ListQuery;

    public MethodologyGR_Dao(DaoConfig config) {
        super(config);
    }
    
    public MethodologyGR_Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"METHODOLOGY_GR_\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BACKGROUND\" TEXT," + // 1: background
                "\"LOGO\" TEXT," + // 2: logo
                "\"METHODOLOGY_ID\" INTEGER NOT NULL );"); // 3: methodology_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"METHODOLOGY_GR_\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MethodologyGR_ entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String background = entity.getBackground();
        if (background != null) {
            stmt.bindString(2, background);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(3, logo);
        }
        stmt.bindLong(4, entity.getMethodology_id());
    }

    @Override
    protected void attachEntity(MethodologyGR_ entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MethodologyGR_ readEntity(Cursor cursor, int offset) {
        MethodologyGR_ entity = new MethodologyGR_( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // background
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // logo
            cursor.getLong(offset + 3) // methodology_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MethodologyGR_ entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBackground(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLogo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMethodology_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MethodologyGR_ entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MethodologyGR_ entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "methodologyGR_List" to-many relationship of MethodologyGR. */
    public List<MethodologyGR_> _queryMethodologyGR_MethodologyGR_List(long methodology_id) {
        synchronized (this) {
            if (methodologyGR_MethodologyGR_ListQuery == null) {
                QueryBuilder<MethodologyGR_> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Methodology_id.eq(null));
                methodologyGR_MethodologyGR_ListQuery = queryBuilder.build();
            }
        }
        Query<MethodologyGR_> query = methodologyGR_MethodologyGR_ListQuery.forCurrentThread();
        query.setParameter(0, methodology_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMethodologyGRDao().getAllColumns());
            builder.append(" FROM METHODOLOGY_GR_ T");
            builder.append(" LEFT JOIN METHODOLOGY_GR T0 ON T.\"METHODOLOGY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MethodologyGR_ loadCurrentDeep(Cursor cursor, boolean lock) {
        MethodologyGR_ entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        MethodologyGR methodologyGR = loadCurrentOther(daoSession.getMethodologyGRDao(), cursor, offset);
         if(methodologyGR != null) {
            entity.setMethodologyGR(methodologyGR);
        }

        return entity;    
    }

    public MethodologyGR_ loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MethodologyGR_> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MethodologyGR_> list = new ArrayList<MethodologyGR_>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MethodologyGR_> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MethodologyGR_> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
