package com.audacityit.audacity.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OVERVIEWCONTENT_GR".
 */
public class OverviewcontentGR {

    private Long id;
    private String title;
    private String background;
    private String logo;
    private String moto;
    private String count1text;
    private String count1no;
    private String count2text;
    private String count2no;
    private String count3text;
    private String count3no;

    public OverviewcontentGR() {
    }

    public OverviewcontentGR(Long id) {
        this.id = id;
    }

    public OverviewcontentGR(Long id, String title, String background, String logo, String moto, String count1text, String count1no, String count2text, String count2no, String count3text, String count3no) {
        this.id = id;
        this.title = title;
        this.background = background;
        this.logo = logo;
        this.moto = moto;
        this.count1text = count1text;
        this.count1no = count1no;
        this.count2text = count2text;
        this.count2no = count2no;
        this.count3text = count3text;
        this.count3no = count3no;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getMoto() {
        return moto;
    }

    public void setMoto(String moto) {
        this.moto = moto;
    }

    public String getCount1text() {
        return count1text;
    }

    public void setCount1text(String count1text) {
        this.count1text = count1text;
    }

    public String getCount1no() {
        return count1no;
    }

    public void setCount1no(String count1no) {
        this.count1no = count1no;
    }

    public String getCount2text() {
        return count2text;
    }

    public void setCount2text(String count2text) {
        this.count2text = count2text;
    }

    public String getCount2no() {
        return count2no;
    }

    public void setCount2no(String count2no) {
        this.count2no = count2no;
    }

    public String getCount3text() {
        return count3text;
    }

    public void setCount3text(String count3text) {
        this.count3text = count3text;
    }

    public String getCount3no() {
        return count3no;
    }

    public void setCount3no(String count3no) {
        this.count3no = count3no;
    }

}
