package com.audacityit.audacity.greendao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.audacityit.audacity.greendao.db.PortfolioGR_;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PORTFOLIO_GR_".
*/
public class PortfolioGR_Dao extends AbstractDao<PortfolioGR_, Long> {

    public static final String TABLENAME = "PORTFOLIO_GR_";

    /**
     * Properties of entity PortfolioGR_.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Image = new Property(2, String.class, "image", false, "IMAGE");
        public final static Property Portfolio_id = new Property(3, long.class, "portfolio_id", false, "PORTFOLIO_ID");
    };

    private DaoSession daoSession;

    private Query<PortfolioGR_> portfolioGR_PortfolioGR_ListQuery;

    public PortfolioGR_Dao(DaoConfig config) {
        super(config);
    }
    
    public PortfolioGR_Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PORTFOLIO_GR_\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"IMAGE\" TEXT," + // 2: image
                "\"PORTFOLIO_ID\" INTEGER NOT NULL );"); // 3: portfolio_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PORTFOLIO_GR_\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PortfolioGR_ entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(3, image);
        }
        stmt.bindLong(4, entity.getPortfolio_id());
    }

    @Override
    protected void attachEntity(PortfolioGR_ entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PortfolioGR_ readEntity(Cursor cursor, int offset) {
        PortfolioGR_ entity = new PortfolioGR_( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // image
            cursor.getLong(offset + 3) // portfolio_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PortfolioGR_ entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPortfolio_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PortfolioGR_ entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PortfolioGR_ entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "portfolioGR_List" to-many relationship of PortfolioGR. */
    public List<PortfolioGR_> _queryPortfolioGR_PortfolioGR_List(long portfolio_id) {
        synchronized (this) {
            if (portfolioGR_PortfolioGR_ListQuery == null) {
                QueryBuilder<PortfolioGR_> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Portfolio_id.eq(null));
                portfolioGR_PortfolioGR_ListQuery = queryBuilder.build();
            }
        }
        Query<PortfolioGR_> query = portfolioGR_PortfolioGR_ListQuery.forCurrentThread();
        query.setParameter(0, portfolio_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPortfolioGRDao().getAllColumns());
            builder.append(" FROM PORTFOLIO_GR_ T");
            builder.append(" LEFT JOIN PORTFOLIO_GR T0 ON T.\"PORTFOLIO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PortfolioGR_ loadCurrentDeep(Cursor cursor, boolean lock) {
        PortfolioGR_ entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PortfolioGR portfolioGR = loadCurrentOther(daoSession.getPortfolioGRDao(), cursor, offset);
         if(portfolioGR != null) {
            entity.setPortfolioGR(portfolioGR);
        }

        return entity;    
    }

    public PortfolioGR_ loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PortfolioGR_> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PortfolioGR_> list = new ArrayList<PortfolioGR_>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PortfolioGR_> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PortfolioGR_> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
