package com.audacityit.audacity.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SLIDE_BAR_GR".
 */
public class SlideBarGR {

    private Long id;
    private String background;
    private String logo;
    private String phone;
    private String email;
    private String web;

    public SlideBarGR() {
    }

    public SlideBarGR(Long id) {
        this.id = id;
    }

    public SlideBarGR(Long id, String background, String logo, String phone, String email, String web) {
        this.id = id;
        this.background = background;
        this.logo = logo;
        this.phone = phone;
        this.email = email;
        this.web = web;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWeb() {
        return web;
    }

    public void setWeb(String web) {
        this.web = web;
    }

}
