package com.audacityit.audacity.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPLASH_GR".
 */
public class SplashGR {

    private Long id;
    private String logo;
    private String bgcolor;

    public SplashGR() {
    }

    public SplashGR(Long id) {
        this.id = id;
    }

    public SplashGR(Long id, String logo, String bgcolor) {
        this.id = id;
        this.logo = logo;
        this.bgcolor = bgcolor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getBgcolor() {
        return bgcolor;
    }

    public void setBgcolor(String bgcolor) {
        this.bgcolor = bgcolor;
    }

}
