package com.audacityit.audacity.greendao.db;

import java.util.List;
import com.audacityit.audacity.greendao.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TESTIMONIAL_GR".
 */
public class TestimonialGR {

    private Long id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TestimonialGRDao myDao;

    private List<TestimonialGR_> testimonialGR_List;

    public TestimonialGR() {
    }

    public TestimonialGR(Long id) {
        this.id = id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTestimonialGRDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<TestimonialGR_> getTestimonialGR_List() {
        if (testimonialGR_List == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TestimonialGR_Dao targetDao = daoSession.getTestimonialGR_Dao();
            List<TestimonialGR_> testimonialGR_ListNew = targetDao._queryTestimonialGR_TestimonialGR_List(id);
            synchronized (this) {
                if(testimonialGR_List == null) {
                    testimonialGR_List = testimonialGR_ListNew;
                }
            }
        }
        return testimonialGR_List;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTestimonialGR_List() {
        testimonialGR_List = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
